### ISSUE TITLE
About stop and resume the animation

### ISSUE THREAD

**Issue by LycsHub** [aak74/vuejs-sort#1]
I run the code well, and find the function "visualize" in “App.vue”,
I know the function is  visualize the sort and bind the method with Click Start,
but I dont know how to stop and resume the animation control by the javascript tickle
Cloud tell me how stop & resume it ? ths

**Comment by aak74** [comment]
There is nothing code for stop and resume animation. If you want to realize it you must modifying `sort` function in BubbleSort and QuickSort.

**Comment by LycsHub** [comment]
ths,I got it :)
